### ISSUE TITLE
about not scan wifi

### ISSUE THREAD

**Issue by leiyong316** [younata/ios-WifiTool#2]
@younata   I download this project,   running  variable  networks and devices returns nil.  
please help me ,  thank you very much. 

xcode 6.3.1,    devices  iphone4  IOS7 , no  jailbreak

- (void)viewDidLoad
{
    [super viewDidLoad];

    // Uncomment the following line to preserve selection between presentations.
    // self.clearsSelectionOnViewWillAppear = NO;
 
    // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
    // self.navigationItem.rightBarButtonItem = self.editButtonItem;
    
    CFArrayRef networks = WiFiManagerClientCopyNetworks(manager);
    if (networks) {
        NSLog(@"%@", networks);
        CFRelease(networks);
    }
    
    CFArrayRef devices = WiFiManagerClientCopyDevices(manager);
	if (devices) {
        NSLog(@"devices (%@) has %ld devices", devices, CFArrayGetCount(devices));
        WiFiDeviceClientRef client = (WiFiDeviceClientRef)CFArrayGetValueAtIndex(devices, 0);
        WiFiDeviceClientScanAsync(client, (__bridge CFDictionaryRef)[NSDictionary dictionary], scan_callback, 0);
    }
    
	WiFiManagerClientScheduleWithRunLoop(manager, CFRunLoopGetCurrent(), kCFRunLoopDefaultMode);
}

**Comment by younata** [comment]
Yeah, I never actually got this to work myself, and it's not very high on my list of priorities.

Sorry about the disappointment.

**Comment by leiyong316** [comment]
thanks, I did it
