### ISSUE TITLE
WiFiManagerClientCopyDevices return 0x0?

### ISSUE THREAD

**Issue by goodcyg** [younata/ios-WifiTool#3]
WiFiManagerClientCopyDevices return 0x0

**Comment by goodcyg** [comment]
my system is xcode 7.2.1 ios9.2

**Comment by younata** [comment]
I never got it working even on iOS 7, sorry.

**Comment by goodcyg** [comment]
You try to Xcode 7.2.1 ios9.2，To give a solution？

**Comment by younata** [comment]
Nope, I don't even think of this project nowadays.

**Comment by goodcyg** [comment]
why？？？

**Comment by younata** [comment]
Because I worked on it 2 years ago, never got it working, and open sourced it in the event that someone smarter than I decided to pick it up and look at it. My interests lie elsewhere nowadays.

**Comment by goodcyg** [comment]
You put him in the maintenance of the convenience of people who are interested in learning about, not very happy thing?
